WATCHLIST = [
    'PLTR',
    'RIVN',
    'SNAP',
    'COIN',
    'SOFI',
    'NIO',
    'LCID',
    'AMC'
]

PREDICTION_THRESHOLD = 0.55
POSITION_SIZE_USD = 1000
MAX_POSITIONS = 8
MAX_DAILY_LOSS = 500
TRADE_INTERVAL_SECONDS = 60
ALLOW_SHORTING = True

MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 16
MARKET_CLOSE_MINUTE = 0

STOP_LOSS_PCT = 0.02
TAKE_PROFIT_PCT = 0.03

MODEL_RELOAD_INTERVAL_HOURS = 6

USE_REALISTIC_COSTS = True
ENABLE_TAX_TRACKING = True

LIQUIDATE_EOD = False
EOD_LIQUIDATION_TIME = "15:45"
MAX_POSITION_HOLD_HOURS = 24
